### ISSUE TITLE
Sizing issue in inference using pre-trained models

### ISSUE THREAD

**Issue by amil-rp-work** [lucasxlu/TransFBP#2]
Hey @lucasxlu 
I tried following your instructions, however I am facing some issues in inferencing the pre-trained models.
I kept the [infer.py](https://github.com/lucasxlu/TransFBP/blob/master/main/infer.py) almost same, but just changed paths for `vgg-face.mat` and used `joblib` to load the `BayesRegression model`. However I face the following error - 

`ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8192 is different from 100352)`

I think you have trained the model using some other layer(and not `conv5_1`) or maybe 2 FC layers concatenated with each other(4096+4096)?

**Comment by lucasxlu** [comment]
Yes, you are right. I forget to mention that the pretrained BayesRegression model I shared is trained on [SCUT-FBP5500](https://arxiv.org/pdf/1801.06345.pdf) dataset (since it's the largest benchmark dataset for research, but not presented in our 
 paper since it was not introduced at that time). I use **conv5_1** features on [SCUT-FBP](http://www.hcii-lab.net/data/scut-fbp/en/introduce.html) and [HotOrNot](https://www.researchgate.net/publication/261595808_Female_Facial_Beauty_Dataset_ECCV2010_v10) datasets, and **fc6 + fc7 concatenation** features are adopted for fitting [SCUT-FBP5500](https://arxiv.org/pdf/1801.06345.pdf). Sorry for the inconvenience. The modification of feature extraction can be found from [this method](https://github.com/lucasxlu/TransFBP/blob/0183a744a4705291c265f422e2f55798a1a8fdfe/util/file_util.py#L59). I will fix this issue ASAP.

**Comment by lucasxlu** [comment]
hi, @amil-rp-work  I have updated [infer.py](https://github.com/lucasxlu/TransFBP/blob/master/main/infer.py) in master branch, you can try it again.

**Comment by amil-rp-work** [comment]
Thanks a lot @lucasxlu. Works perfectly now 👍
